services:
  # --- SERVIDOR WEB ---
  web:
    # IMPORTANTE: Ahora es ./ porque estamos en la misma carpeta
    build: ./sylo-web
    container_name: sylo-web
    ports:
      - "8000:80"
    volumes:
      - ./sylo-web:/var/www/html
      - ./buzon-pedidos:/buzon
    depends_on:
      - kylo-main-db
    networks:
      - sylo-network

  # --- BASE DE DATOS ---
  kylo-main-db:
    image: mysql:5.7
    container_name: kylo-main-db
    environment:
      MYSQL_DATABASE: kylo_main_db
      MYSQL_USER: sylo_app
      MYSQL_PASSWORD: sylo_app_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # Ruta corregida también aquí
      - ./sylo-web/init_kylo.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - sylo-network

volumes:
  db_data:

networks:
  sylo-network:
    driver: bridge