version: '3.8'

services:
  # --- 1. SERVIDOR WEB (PHP + Apache + Cliente Docker) ---
  web:
    build: ./sylo-web
    container_name: sylo-web
    ports:
      - "8000:80"
    
    # Puente mágico para que PHP hable con el Host (tu Linux)
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./sylo-web:/var/www/html
      - ./buzon-pedidos:/buzon
      - /var/run/docker.sock:/var/run/docker.sock # Para que PHP pueda usar Docker
    depends_on:
      - kylo-main-db
    networks:
      - sylo-network

  # --- 2. BASE DE DATOS DEL GESTOR (MySQL Clásico para usuarios/pedidos) ---
  kylo-main-db:
    image: mysql:5.7
    container_name: kylo-main-db
    environment:
      MYSQL_DATABASE: kylo_main_db
      MYSQL_USER: sylo_app
      MYSQL_PASSWORD: sylo_app_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./sylo-web/init_kylo.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - sylo-network

  # --- 3. NUEVO: KYLO DB ENGINE (Tu Motor Java Propio) ---
  kylo-db:
    build: ./Kylo             # Busca el Dockerfile dentro de la carpeta Kylo
    container_name: kylo-db-core
    ports:
      - "8082:8080"           # Mapeamos la GUI de Kylo al puerto 8082 de tu PC
      - "5000:5000"           # Puerto de datos TCP de Kylo
    networks:
      - sylo-network          # Se conecta a la misma red para hablar con la web si hace falta
    restart: unless-stopped

volumes:
  db_data:

networks:
  sylo-network:
    driver: bridge