version: '3.8'

services:
  # --- 1. SERVIDOR WEB (PHP + Apache + Cliente Docker) ---
  web:
    build: ./sylo-web
    container_name: sylo-web
    ports:
      - "8000:80"

    # Puente mágico para que PHP hable con el Host (tu Linux)
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./sylo-web:/var/www/html
      - ./buzon-pedidos:/buzon
      - /var/run/docker.sock:/var/run/docker.sock # Para que PHP pueda usar Docker
    depends_on:
      - kylo-main-db
    networks:
      - sylo-network

  # --- 2. BASE DE DATOS DEL GESTOR (MySQL Clásico para usuarios/pedidos) ---
  kylo-main-db:
    image: mysql:5.7
    container_name: kylo-main-db
    environment:
      MYSQL_DATABASE: kylo_main_db
      MYSQL_USER: sylo_app
      MYSQL_PASSWORD: sylo_app_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./sylo-web/init_kylo.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - sylo-network

volumes:
  db_data:


networks:
  sylo-network:
    driver: bridge
