version: '3.8'

services:
  # --- SERVIDOR WEB (PHP + Apache) ---
  web:
    build: ./sylo-web
    container_name: sylo-web
    ports:
      - "8000:80"
    
    # ðŸ”¥ ESTO ES LO NUEVO: El puente mÃ¡gico hacia tu Host (Linux)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ---------------------------------------------------------

    volumes:
      - ./sylo-web:/var/www/html
      - ./buzon-pedidos:/buzon
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kylo-main-db
    networks:
      - sylo-network

  # --- BASE DE DATOS (Cerebro) ---
  kylo-main-db:
    image: mysql:5.7
    container_name: kylo-main-db
    environment:
      MYSQL_DATABASE: kylo_main_db
      MYSQL_USER: sylo_app
      MYSQL_PASSWORD: sylo_app_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./sylo-web/init_kylo.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - sylo-network

volumes:
  db_data:

networks:
  sylo-network:
    driver: bridge